"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, Sparkles } from "lucide-react";

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      q: "What file formats can I upload to LecturePilot?",
      a: "LecturePilot accepts PDF slide decks, handwritten class notes (scans/photos), MP4/MOV lecture videos, and audio recordings. Our multimodal pipeline parses visual diagrams, formulas, text, and spoken words synchronously.",
    },
    {
      q: "How does citation grounding work with zero hallucinations?",
      a: "Every answer generated by LecturePilot cross-references the ingested vector index. The AI explicitly cites the exact slide number (e.g. [Slide 14]) or audio/video timestamp (e.g. [Video 44:18]). Clicking any citation brings up the verbatim source text.",
    },
    {
      q: "How does the active recall & spaced repetition system work?",
      a: "LecturePilot extracts flashcard decks using the SuperMemo SM-2 algorithm. When you review, you rate each card (Again, Hard, Good, Easy) which schedules the optimal review intervals so facts move from short-term to long-term memory.",
    },
    {
      q: "How are quizzes generated?",
      a: "Our system identifies key conceptual pivot points and common professor exam traps from your lecture. It constructs multiple-choice questions with plausible distractors, providing immediate feedback on why the right answer works and why wrong choices fail.",
    },
    {
      q: "How is LecturePilot accelerated for the Nebius x NVIDIA Hackathon?",
      a: "We leverage NVIDIA NIM inference microservices (such as Llama 3 and NeMo Retriever) running on Nebius Cloud GPU infrastructure. This provides sub-second semantic retrieval and ultra-responsive Socratic chat streaming.",
    },
    {
      q: "Is student coursework kept private?",
      a: "Yes. All uploaded lecture files and student interactions are strictly encrypted at rest and in transit. Your coursework is never used to train public models.",
    },
  ];

  return (
    <section id="faq" className="relative scroll-mt-20 px-5 py-20 lg:px-8 lg:py-28 border-t border-[#F3E8EE] dark:border-[#2C2630]">
      <div className="mx-auto max-w-3xl">
        {/* Header */}
        <div className="text-center">
          <div className="inline-flex items-center gap-1.5 rounded-full border border-[#F3E8EE] dark:border-[#2C2630] bg-[#FDF2F8] dark:bg-[#1A181E] px-3.5 py-1 text-xs font-medium text-[#2D2A32] dark:text-[#FAF8FA]">
            <Sparkles className="h-3 w-3 text-[#F4B6C2]" />
            <span>Questions & Answers 🌸</span>
          </div>

          <h2 className="mt-4 text-3xl font-extrabold tracking-tight text-[#2D2A32] dark:text-[#FAF8FA] sm:text-4xl">
            Frequently Asked Questions
          </h2>

          <p className="mt-3.5 text-sm sm:text-base leading-relaxed text-[#6B6873] dark:text-[#C8C1C5]">
            Everything you need to know about LecturePilot&apos;s AI learning assistant.
          </p>
        </div>

        {/* Accordion list */}
        <div className="mt-14 space-y-3">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.3, delay: idx * 0.04 }}
                className={`overflow-hidden rounded-2xl border transition-colors ${
                  isOpen
                    ? "border-[#F4B6C2] bg-[#FDF2F8]/70 dark:bg-[#1F1C24] shadow-2xs"
                    : "border-[#F3E8EE] dark:border-[#2C2630] bg-white dark:bg-[#1A181E] hover:border-[#F4B6C2]/50"
                }`}
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="flex w-full items-center justify-between p-5 text-left text-sm sm:text-base font-semibold text-[#2D2A32] dark:text-[#FAF8FA]"
                  aria-expanded={isOpen}
                >
                  <span className="pr-4">{faq.q}</span>
                  <div
                    className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[#6B6873] dark:text-[#C8C1C5] transition-transform duration-200 ${
                      isOpen ? "rotate-180 text-[#F4B6C2]" : ""
                    }`}
                  >
                    <ChevronDown className="h-4 w-4" />
                  </div>
                </button>

                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.2, ease: "easeInOut" }}
                    >
                      <div className="px-5 pb-5 pt-1 text-xs sm:text-sm leading-relaxed text-[#6B6873] dark:text-[#C8C1C5] border-t border-[#F3E8EE] dark:border-[#2C2630]">
                        {faq.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
